"""Dormant OpenAI Agents SDK foundations for the text runtime migration."""

from agent.text_runtime.openai_agents.agents import (
    CRISIS_AGENT_NAME,
    GUIDED_EXERCISE_AGENT_NAME,
    THERAPEUTIC_AGENT_NAME,
    OpenAITextAgentRoster,
    build_crisis_response_agent,
    build_guided_exercise_agent,
    build_openai_text_agent_roster,
    build_therapeutic_agent,
)
from agent.text_runtime.openai_agents.context import (
    GroundedToolCallRecord,
    GroundedToolStatus,
    MemoryActionType,
    MemoryReadActionType,
    MemoryToolCallRecord,
    OpenAITextRunContext,
)
from agent.text_runtime.openai_agents.grounded_tools import (
    GroundedLookupToolResult,
    answer_grounded_lookup,
    build_grounded_lookup_tools,
    execute_grounded_lookup_tool,
)
from agent.text_runtime.openai_agents.memory_tools import (
    MemoryToolResult,
    build_memory_tools,
    MemoryReadToolResult,
    build_read_only_memory_tools,
    cancel_memory_deletion,
    confirm_memory_deletion,
    execute_memory_tool_action,
    execute_read_only_memory_action,
    prepare_memory_deletion_by_index,
    prepare_memory_deletion_by_query,
    save_response_preference,
    set_proactive_memory_recall,
    show_memory_status,
    show_saved_memory,
)

__all__ = [
    "CRISIS_AGENT_NAME",
    "GUIDED_EXERCISE_AGENT_NAME",
    "THERAPEUTIC_AGENT_NAME",
    "GroundedLookupToolResult",
    "GroundedToolCallRecord",
    "GroundedToolStatus",
    "MemoryActionType",
    "MemoryReadToolResult",
    "MemoryReadActionType",
    "MemoryToolResult",
    "MemoryToolCallRecord",
    "OpenAITextAgentRoster",
    "OpenAITextRunContext",
    "answer_grounded_lookup",
    "build_crisis_response_agent",
    "build_guided_exercise_agent",
    "build_grounded_lookup_tools",
    "build_memory_tools",
    "build_openai_text_agent_roster",
    "build_read_only_memory_tools",
    "build_therapeutic_agent",
    "cancel_memory_deletion",
    "confirm_memory_deletion",
    "execute_grounded_lookup_tool",
    "execute_memory_tool_action",
    "execute_read_only_memory_action",
    "prepare_memory_deletion_by_index",
    "prepare_memory_deletion_by_query",
    "save_response_preference",
    "set_proactive_memory_recall",
    "show_memory_status",
    "show_saved_memory",
]
