"""Canonical span and event names for agent observability."""

from __future__ import annotations

RUNTIME_TEXT_TURN = "runtime.text_turn"
RUNTIME_VOICE_SESSION = "runtime.voice_session"
REALTIME_SESSION_CONFIG_BUILT = "realtime.session.config_built"
VOICE_CRISIS_RESOURCE_LOOKUP_PERSISTED = "voice.crisis_resource_lookup.persisted"
VOICE_RESPONSE_FINALIZED = "voice.response.finalized"
VOICE_TOOL_COMPLETED = "voice.tool.completed"
VOICE_TOOL_DISPATCH = "voice.tool.dispatch"
VOICE_TOOL_FAILED = "voice.tool.failed"
VOICE_TURN_STATE_BUILT = "voice.turn.state_built"
ROUTING_DECISION = "routing.decision"
MEMORY_READ = "memory.read"
MEMORY_READ_COMPLETED = "memory.read.completed"
MEMORY_READ_SKIPPED = "memory.read.skipped"
MEMORY_WRITE_POLICY = "memory.write_policy"
MEMORY_WRITE_APPROVED = "memory.write.approved"
MEMORY_WRITE_PERSISTED = "memory.write.persisted"
MEMORY_WRITE_SUPPRESSED = "memory.write.suppressed"
SDK_OPENAI_CALL = "sdk.openai.call"
SDK_OPENAI_CALL_COMPLETED = "sdk.openai.call.completed"
TOOL_DISPATCH = "tool.dispatch"
SAFETY_ASSESS = "safety.assess"
SAFETY_ASSESS_COMPLETED = "safety.assess.completed"
RUNTIME_TEXT_TURN_FINALIZED = "runtime.text_turn.finalized"
AUDIT_CRISIS_LOG_APPEND = "audit.crisis_log.append"
GUIDED_EXERCISE_STEP = "guided_exercise.step"
